### ISSUE TITLE
MapView onRegionChange/onRegionChangeComplete wrong definition

### ISSUE THREAD

**Issue by jr360codelab** [sgny/reason-react-native-maps#6]
In `MapView` `onRegionChange/onRegionChangeComplete` `Region.t` is passed directly, not via `ReactNative.Event.syntheticEvent('a)`

**Comment by sgny** [comment]
Thanks for bringing this up. I implemented them to documentation of `react-native-maps` and while I tested a few features beyond what I use myself, I have not been able to test everything. I'm glad that there is another user of these bindings.

I have only updated the repo for the moment, I'm working on another commit and I will publish another `npm` package. Since the source documentation is also incorrect, I will try to push a PR there as well.

**Comment by jr360codelab** [comment]
Thanks, it's working fine with the latest commit.
